name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ github.repository_owner }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }} .
          docker build -t ${{ github.repository_owner }}/${{ secrets.DOCKER_REPOSITORY }}:latest .
          docker push ${{ github.repository_owner }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
          docker push ${{ github.repository_owner }}/${{ secrets.DOCKER_REPOSITORY }}:latest
