name: "Build and Publish Docker Image"

on:
  workflow_run:
    workflows: ["CodeQL Analysis"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if CodeQL Analysis was successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CodeQL Analysis results
        uses: actions/download-artifact@v3
        with:
          name: codeql-results

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            lejz0/vehicle-inspection-app:latest
